# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='edited',
            field=models.DateTimeField(null=True, verbose_name='Edited'),
        ),
        migrations.AlterField(
            model_name='question',
            name='edited',
            field=models.DateTimeField(null=True, verbose_name='Edited'),
        ),
    ]
